services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=thuanhai123
      - MYSQL_DATABASE=TodoList
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    ports:
      - '3307:3306'
    networks:
      - app-network
  backend:
    build: .
    container_name: backend-todo
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - HOST_REDIS=redis
      - PORT_REDIS=6379
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
