services:
  db:
    image: mysql:8
    container_name: mysql-db
    env_file:
      - .env.docker
    ports:
      - '${MYSQL_PORT}:3306'
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-server
    env_file:
      - .env.docker
    ports:
      - '${PORT_REDIS}:6379'
    networks:
      - app-network

  backend:
    build: .
    container_name: backend-todo
    env_file:
      - .env.docker
    ports:
      - '${PORT}:3000'
      - '${WS_PORT}:3000'
    depends_on:
      - db
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
